// ============================================================
// HIVE SETUP — hive_init.dart
// ============================================================
// This is the ONE file that knows about Hive boxes and setup.
// Everything else in the app talks to services, not Hive.
//
// Call HiveInit.init() once at the very start of your app
// in main.dart — before runApp().
//
// BOX NAMES are constants here so we never typo a string.
// ============================================================
// ============================================================
// HIVE SETUP — hive_init.dart — Fixed
// ============================================================
// Change from previous version:
//   Added sessionBox — a plain untyped Box used exclusively to
//   store the currently logged-in user's ID string.
//
//   WHY: Hive typed boxes (Box<UserModel>) cannot safely store
//   string values under arbitrary keys alongside model objects.
//   Trying to do so caused the registration crash (Bug 1).
//   The fix is a second, separate untyped box just for session data.
// ============================================================

import 'package:hive_flutter/hive_flutter.dart';
import 'user_model.dart';
import 'scan_log_model.dart';
import 'points_data_model.dart';

// ── Generated adapters (from build_runner) ──────────────────
// After you run: flutter pub run build_runner build
// Hive generates these adapter files automatically.
// They teach Hive how to read/write your model objects.
//import 'user_model.g.dart';
//import 'scan_log_model.g.dart';
//import 'points_data_model.g.dart';

class HiveInit {
  // ── Box Name Constants ──────────────────────────────────
  // Use these instead of raw strings everywhere.
  // If you ever rename a box, you only change it here.
  static const String userBox = 'userBox';
  static const String scanBox = 'scanBox';
  static const String pointsBox = 'pointsBox';
  static const String sessionBox = 'sessionBox'; // NEW: separate session box

  // ── Session Key ─────────────────────────────────────────
  // We store the currently logged-in user's ID under this key
  // in the userBox so we can restore the session on app restart.
  static const String sessionKey = 'currentUserId';

  // ── Main Init Function ───────────────────────────────────
  // Call this ONCE in main.dart before runApp()
  static Future<void> init() async {
    // 1. Initialize Hive with Flutter path provider
    //    This sets the storage directory to the app's documents folder
    await Hive.initFlutter();

    // 2. Register adapters — one per model
    //    Hive needs these to know how to encode/decode your objects.
    //    The .g.dart files are auto-generated by build_runner.
    Hive.registerAdapter(UserModelAdapter());
    Hive.registerAdapter(ScanLogModelAdapter());
    Hive.registerAdapter(PointsDataModelAdapter());

    // 3. Open all boxes upfront
    //    Think of opening a box like connecting to a DB table.
    //    We open them all at startup so services never need to wait.
    await Hive.openBox<UserModel>(userBox);
    await Hive.openBox<ScanLogModel>(scanBox);
    await Hive.openBox<PointsDataModel>(pointsBox);

    // NEW: Open untyped box for session string only
    // No type parameter — this box holds plain String values
    await Hive.openBox(sessionBox);
  }
}
